apiVersion: v1
kind: Service
metadata:
  name: {{ include "laa-inquests-internal-ui.fullname" . }}
  labels:
    {{- include "laa-inquests-internal-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "laa-inquests-internal-ui.selectorLabels" . | nindent 4 }}