name: CI

on:
  push:
    branches:
      - main
  pull_request:
    # From docs: if no activity types are specified, the workflow runs when a pull request is opened or reopened or when the head branch of the pull request is updated.
    paths:
      - "deploy/**"
      - ".github/**"
      - "src/**"
      - "tests/**"
      - "Dockerfile"
      - "yarn.lock"
  workflow_dispatch:
    inputs:
      environment:
        description: "Github deployment environment"
        required: false
        default: "uat"
        type: choice
        options:
          - uat

jobs:
  code-linting:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node and Dependencies
        uses: ./.github/actions/setup-node

      - name: Run ESLint
        run: yarn lint

  code-security-audit:
    name: Code Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node and Dependencies
        uses: ./.github/actions/setup-node

      - name: Run security audit
        run: yarn npm audit

  snyk:
    name: Snyk scan docker image
    runs-on: ubuntu-latest
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build local Docker image
        working-directory: ${{ github.workspace }}
        run: |
          docker build -t laa-inquests-ui ./
          docker save laa-inquests-ui -o image.tar

      - name: Run Snyk to scan Docker image from tarball
        uses: snyk/actions/docker@master
        with:
          image: image.tar
          args: --docker --severity-threshold=high --policy-path=.snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Monitor docker image using Snyk
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          image: laa-inquests-ui:scan
          args: --file=Dockerfile --policy-path=.snyk

  unit-tests:
    name: Mocha Unit Tests
    uses: ./.github/workflows/unit-tests.yaml
    needs:
      - build-image

  e2e-tests:
    name: Playwright Tests
    uses: ./.github/workflows/e2e-tests.yaml
    needs:
      - build-image

  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    environment: uat
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up AWS credentials for ECR and Kubernetes
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}

      - uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076
        id: login-ecr

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push image with local action
        uses: ./.github/actions/build-and-push
        with:
          image_registry: ${{ secrets.ECR_REGISTRY_URL }}
          image_repo: ${{ vars.ECR_REPOSITORY }}
          dockerfile_path: Dockerfile
          image_tag: ${{ github.sha }}
  deploy:
    if: ${{ !contains(github.actor, '[bot]') }}
    runs-on: ubuntu-latest
    environment: uat
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    needs:
      - e2e-tests
      - unit-tests
      - snyk
      - build-image
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Deploy to uat
        uses: ./.github/actions/deploy
        with:
          app-environment: uat
          kube-cert: ${{ secrets.KUBE_CERT }}
          kube-token: ${{ secrets.KUBE_TOKEN }}
          kube-cluster: ${{ secrets.KUBE_CLUSTER }}
          kube-namespace: ${{ secrets.KUBE_NAMESPACE }}
          ecr-repository: ${{ vars.ECR_REPOSITORY }}
          ecr-registry_url: ${{ secrets.ECR_REGISTRY_URL }}
          ecr-role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          ecr-region: ${{ vars.ECR_REGION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-sha: ${{ github.sha }}
          github-ref-name: ${{ github.ref_name }}
          github-head-ref: ${{ github.head_ref }}
          image-tag: ${{ github.sha }}
